# Generated by Django 2.1.1 on 2018-10-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
