# Generated by Django 2.1.1 on 2018-11-20 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigIntegerField(default=1, primary_key=True, serialize=False)),
                ('feedback', models.IntegerField(choices=[(-1, 'Negative'), (0, 'Neutral'), (1, 'Good')])),
                ('opinion', models.CharField(max_length=255)),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_left_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
