# Generated by Django 2.1.1 on 2018-11-21 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20181120_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
